create table if not exists public.timetable_collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  year integer not null check (year >= 0 and year <= 3000),
  semester text not null,
  title varchar(150) not null,
  title_custom boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists timetable_collections_user_year_semester_idx
  on public.timetable_collections(user_id, year, semester, updated_at desc);

alter table public.timetables
  add column if not exists timetable_id bigint
  references public.timetable_collections(id) on delete cascade;

insert into public.timetable_collections (user_id, year, semester, title, created_at, updated_at)
select
  t.user_id,
  coalesce(t.year, 2026) as year,
  coalesce(t.semester, '2') as semester,
  concat(
    coalesce(t.year, 2026),
    '년 ',
    case coalesce(t.semester, '2')
      when '1' then '1학기'
      when '2' then '2학기'
      when 'summer' then '여름학기'
      when 'winter' then '겨울학기'
      else concat(coalesce(t.semester, '2'), '학기')
    end,
    ' 시간표'
  ) as title,
  min(coalesce(t.created_at, now())) as created_at,
  max(coalesce(t.updated_at, t.created_at, now())) as updated_at
from public.timetables t
left join public.timetable_collections c
  on c.user_id = t.user_id
 and c.year = coalesce(t.year, 2026)
 and c.semester = coalesce(t.semester, '2')
where c.id is null
group by t.user_id, coalesce(t.year, 2026), coalesce(t.semester, '2');

update public.timetables t
set timetable_id = c.id
from public.timetable_collections c
where t.timetable_id is null
  and c.user_id = t.user_id
  and c.year = coalesce(t.year, 2026)
  and c.semester = coalesce(t.semester, '2');

alter table public.timetables
  alter column timetable_id set not null;

alter table public.timetable_collections enable row level security;

drop policy if exists "timetable_collections_select_own" on public.timetable_collections;
create policy "timetable_collections_select_own" on public.timetable_collections
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "timetable_collections_insert_own" on public.timetable_collections;
create policy "timetable_collections_insert_own" on public.timetable_collections
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "timetable_collections_update_own" on public.timetable_collections;
create policy "timetable_collections_update_own" on public.timetable_collections
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "timetable_collections_delete_own" on public.timetable_collections;
create policy "timetable_collections_delete_own" on public.timetable_collections
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.timetable_collections to authenticated;
grant usage, select on sequence public.timetable_collections_id_seq to authenticated;
