-- KMU Smart Scheduler: Supabase Auth profile + timetable schema
-- Supabase Dashboard > SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  student_id varchar(20) not null unique,
  name varchar(50) not null,
  department varchar(100) not null,
  grade smallint not null check (grade between 1 and 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.timetables (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject varchar(100) not null,
  professor varchar(50) not null default '',
  classroom varchar(100) not null default '',
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  color varchar(10) not null default '#356AE6',
  memo text not null default '',
  created_at timestamptz not null default now(),
  constraint timetable_time_order check (end_time > start_time)
);

create index if not exists timetables_user_weekday_idx
  on public.timetables(user_id, weekday, start_time);

alter table public.profiles enable row level security;
alter table public.timetables enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "timetables_select_own" on public.timetables;
create policy "timetables_select_own" on public.timetables
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "timetables_insert_own" on public.timetables;
create policy "timetables_insert_own" on public.timetables
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "timetables_update_own" on public.timetables;
create policy "timetables_update_own" on public.timetables
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
drop policy if exists "timetables_delete_own" on public.timetables;
create policy "timetables_delete_own" on public.timetables
  for delete to authenticated using ((select auth.uid()) = user_id);

-- 회원가입 시 auth user_metadata에서 public.profiles를 자동 생성합니다.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, student_id, name, department, grade)
  values (
    new.id,
    new.raw_user_meta_data ->> 'student_id',
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'department',
    (new.raw_user_meta_data ->> 'grade')::smallint
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.timetables to authenticated;
grant usage, select on sequence public.timetables_id_seq to authenticated;
