create table if not exists public.ai_recommended_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_date date not null,
  items jsonb not null default '[]'::jsonb,
  source varchar(20) not null default 'rules',
  message text not null default '',
  context jsonb not null default '{}'::jsonb,
  schedule_version integer not null default 3,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, plan_date),
  constraint ai_recommended_schedules_items_array check (jsonb_typeof(items) = 'array')
);

create index if not exists ai_recommended_schedules_user_date_idx
  on public.ai_recommended_schedules(user_id, plan_date desc);

alter table public.ai_recommended_schedules enable row level security;

drop policy if exists "ai_recommended_schedules_select_own" on public.ai_recommended_schedules;
create policy "ai_recommended_schedules_select_own" on public.ai_recommended_schedules
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "ai_recommended_schedules_insert_own" on public.ai_recommended_schedules;
create policy "ai_recommended_schedules_insert_own" on public.ai_recommended_schedules
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "ai_recommended_schedules_update_own" on public.ai_recommended_schedules;
create policy "ai_recommended_schedules_update_own" on public.ai_recommended_schedules
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "ai_recommended_schedules_delete_own" on public.ai_recommended_schedules;
create policy "ai_recommended_schedules_delete_own" on public.ai_recommended_schedules
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.ai_recommended_schedules to authenticated;
grant usage, select on sequence public.ai_recommended_schedules_id_seq to authenticated;
