-- FastAPI replacement: durable cache and school-event domain for Edge Functions.

alter table public.profiles
  add column if not exists interests text not null default '';

create table if not exists public.kmu_edge_cache (
  cache_key text primary key,
  payload jsonb not null default 'null'::jsonb,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.school_events (
  id bigint generated by default as identity primary key,
  title varchar(250) not null,
  summary text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  apply_deadline timestamptz,
  category varchar(40) not null default '행사',
  source_type varchar(20) not null default 'school',
  department varchar(100) not null default '',
  location varchar(150) not null default '',
  interests text not null default '',
  url varchar(1000) not null default '',
  apply_url varchar(1000) not null default '',
  source_key varchar(180) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists school_events_active_idx
  on public.school_events(ends_at, apply_deadline, starts_at);
create index if not exists school_events_source_idx
  on public.school_events(source_type, starts_at);

create table if not exists public.school_event_favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id bigint not null references public.school_events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, event_id)
);

alter table public.kmu_edge_cache enable row level security;
alter table public.school_events enable row level security;
alter table public.school_event_favorites enable row level security;

drop policy if exists "school_events_read_authenticated" on public.school_events;
create policy "school_events_read_authenticated" on public.school_events
  for select to authenticated using (true);

drop policy if exists "school_event_favorites_select_own" on public.school_event_favorites;
create policy "school_event_favorites_select_own" on public.school_event_favorites
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "school_event_favorites_insert_own" on public.school_event_favorites;
create policy "school_event_favorites_insert_own" on public.school_event_favorites
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "school_event_favorites_delete_own" on public.school_event_favorites;
create policy "school_event_favorites_delete_own" on public.school_event_favorites
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select on public.school_events to authenticated;
grant select, insert, delete on public.school_event_favorites to authenticated;
grant usage, select on sequence public.school_events_id_seq to authenticated;

